//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public string AccountId { get; set; }
        public string MobileCode { get; set; }
        public string SecurityCode { get; set; }
        public string Password { get; set; }
        public string CompanyName { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public Nullable<System.DateTime> ExpireTime { get; set; }
        public string IPAddress { get; set; }
        public string IPAddressName { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<int> EnabledMark { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public Nullable<int> LogOnCount { get; set; }
        public Nullable<int> AmountCount { get; set; }
        public Nullable<bool> IsResetPwd { get; set; }
    }
}
