//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class api2_recycles
    {
        public string arcc_guid { get; set; }
        public string arcc_objectId { get; set; }
        public string arcc_organizeId { get; set; }
        public string arcc_type { get; set; }
        public string arcc_ifdirname { get; set; }
        public string arcc_modifytime { get; set; }
    }
}
