//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class api2_session
    {
        public string apisession_id { get; set; }
        public string apisession_token { get; set; }
        public Nullable<System.DateTime> apisession_currenttime { get; set; }
        public string apisession_companyid { get; set; }
        public string apisession_userid { get; set; }
    }
}
