//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class api2_invite
    {
        public string inv_guid { get; set; }
        public string inv_email { get; set; }
        public string inv_invitecode { get; set; }
        public Nullable<System.DateTime> inv_createdate { get; set; }
        public Nullable<System.DateTime> inv_deadlinedate { get; set; }
        public string inv_roleId { get; set; }
    }
}
