//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class api2_suscribe
    {
        public string asus_guid { get; set; }
        public string asus_userId { get; set; }
        public string asus_objectId { get; set; }
        public string asus_type { get; set; }
        public string asus_organizeId { get; set; }
        public string asus_ifdirname { get; set; }
        public string asus_ifdirupdtime { get; set; }
    }
}
