//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_examinedata
    {
        public string ExamineID { get; set; }
        public string ProjectID { get; set; }
        public string ModelID { get; set; }
        public string ViewID { get; set; }
        public string ViewpointID { get; set; }
        public string LinkType { get; set; }
        public string LinkID { get; set; }
        public string Principal { get; set; }
        public string PrincipalID { get; set; }
        public string RelationMember { get; set; }
        public string RelationMemberID { get; set; }
        public string Examiner { get; set; }
        public string ExaminerID { get; set; }
        public Nullable<System.DateTime> ExamineDate { get; set; }
        public string ExamineRemark { get; set; }
        public string ExamineResult { get; set; }
        public Nullable<System.DateTime> RectificateDate { get; set; }
        public string FloorID { get; set; }
        public string FloorName { get; set; }
        public string FlowPhaseID { get; set; }
        public string FlowPhase { get; set; }
        public string Professional { get; set; }
        public string Category { get; set; }
        public string Placement { get; set; }
        public string FirstCheckerID { get; set; }
        public string FirstCheckerName { get; set; }
        public Nullable<System.DateTime> FirstCheckDate { get; set; }
        public string FirstCheckRemark { get; set; }
        public string FirstCheckResult { get; set; }
        public string SecondCheckerID { get; set; }
        public string SecondCheckerName { get; set; }
        public Nullable<System.DateTime> SecondCheckDate { get; set; }
        public string SecondCheckRemark { get; set; }
        public string SecondCheckResult { get; set; }
        public string ConstructUnit { get; set; }
        public string ConstructUnitID { get; set; }
        public string SubConstructUnit { get; set; }
        public string SubConstructUnitID { get; set; }
        public string Subdivisional { get; set; }
        public string SubdivisionalID { get; set; }
        public string VerifyBatch { get; set; }
        public string VerifyBatchID { get; set; }
        public string Axis { get; set; }
        public string AxisID { get; set; }
        public string ConstructionTeam { get; set; }
        public string ConstructionTeamID { get; set; }
        public Nullable<int> IsDel { get; set; }
        public string ProfessionalID { get; set; }
        public string CategoryID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Title { get; set; }
    }
}
