//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_examinerectification
    {
        public string RectificationID { get; set; }
        public string RectificationOperatorID { get; set; }
        public string RectificationOperator { get; set; }
        public Nullable<int> RectificationOperateFlag { get; set; }
        public Nullable<System.DateTime> RectificationCheckDate { get; set; }
        public string RectificationCheckResult { get; set; }
        public string RectificationRemark { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public string ExamineID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
