//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_drawposinfo
    {
        public string GID { get; set; }
        public string FileId { get; set; }
        public Nullable<int> PosX { get; set; }
        public Nullable<int> PosY { get; set; }
        public string OpId { get; set; }
        public string OpUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ExamineId { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Z { get; set; }
        public string Pixel2MX { get; set; }
        public string Pixel2MY { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public Nullable<int> IsDel { get; set; }
    }
}
