//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_examineattachment
    {
        public string ExamineAttachmentID { get; set; }
        public string ExamineID { get; set; }
        public string AttachmentType { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentUrl { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<int> CheckFlag { get; set; }
        public Nullable<int> IsDel { get; set; }
    }
}
