//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_schedule_participant
    {
        public string Organized_participantId { get; set; }
        public string ScheduleId { get; set; }
        public string UserID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime Updated { get; set; }
        public int Removed { get; set; }
    }
}
