//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_moduleforminstance
    {
        public string FormInstanceId { get; set; }
        public string FormId { get; set; }
        public string FormInstanceJson { get; set; }
        public string ObjectId { get; set; }
        public Nullable<int> SortCode { get; set; }
        public string Description { get; set; }
    }
}
