//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_publicextend
    {
        public string ExtendId { get; set; }
        public string PrimaryId { get; set; }
        public string Extend_1 { get; set; }
        public string Extend_1_Description { get; set; }
        public string Extend_2 { get; set; }
        public string Extend_2_Description { get; set; }
        public string Extend_3 { get; set; }
        public string Extend_3_Description { get; set; }
        public string Extend_4 { get; set; }
        public string Extend_4_Description { get; set; }
        public string Extend_5 { get; set; }
        public string Extend_5_Description { get; set; }
        public string Extend_6 { get; set; }
        public string Extend_6_Description { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
