//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_relation
    {
        public string RelationID { get; set; }
        public string SourceID { get; set; }
        public string SourceType { get; set; }
        public string TargetID { get; set; }
        public string TargetType { get; set; }
        public string CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<int> BR_DeleteMark { get; set; }
    }
}
