//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_issuenewrelation
    {
        public string BINR_ID { get; set; }
        public string BINR_IssueID { get; set; }
        public string BINR_ViewPoint_ModelID { get; set; }
        public string BINR_ViewPointID { get; set; }
        public string BINR_Image2D_ModelID { get; set; }
        public string BINR_Image2DID { get; set; }
        public string BINR_Image2D_Position { get; set; }
    }
}
