//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_issue
    {
        public string IssueId { get; set; }
        public string ProjectID { get; set; }
        public string ModelId { get; set; }
        public string ViewpointID { get; set; }
        public string Title { get; set; }
        public string ImageUrl { get; set; }
        public string Content { get; set; }
        public string IssueStatus { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public string IssueTypeID { get; set; }
        public Nullable<int> DeleteMark { get; set; }
    }
}
