//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_authorizedata
    {
        public string AuthorizeDataId { get; set; }
        public Nullable<int> AuthorizeType { get; set; }
        public Nullable<int> Category { get; set; }
        public string ObjectId { get; set; }
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public string ResourceId { get; set; }
        public Nullable<int> IsRead { get; set; }
        public string AuthorizeConstraint { get; set; }
        public Nullable<int> SortCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
    }
}
