//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_messagequeue
    {
        public string MessageQueueId { get; set; }
        public string MessageContent { get; set; }
        public string ReceiverContact { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<bool> IsPushed { get; set; }
        public Nullable<int> Category { get; set; }
    }
}
