//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_issue_user
    {
        public string Issue_User_Id { get; set; }
        public string IssueId { get; set; }
        public string UserId { get; set; }
        public string IUType { get; set; }
        public Nullable<int> IsRead { get; set; }
    }
}
