//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_fileinfo_version
    {
        public string FileInfoVersionId { get; set; }
        public string FileId { get; set; }
        public int FileVersion { get; set; }
        public string FileSize { get; set; }
        public string CreateUserID { get; set; }
        public string CreateUserName { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
