//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_logext
    {
        public System.Guid ble_guid { get; set; }
        public string bl_guid { get; set; }
        public string ble_organize1Id { get; set; }
        public string ble_organize2Id { get; set; }
        public string ble_roleId { get; set; }
        public string ble_userId { get; set; }
        public string ble_issueId { get; set; }
        public string ble_objecttype { get; set; }
        public string ble_actionname { get; set; }
    }
}
