//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_news
    {
        public string NewsId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string ParentId { get; set; }
        public string Category { get; set; }
        public string FullHead { get; set; }
        public string FullHeadColor { get; set; }
        public string BriefHead { get; set; }
        public string AuthorName { get; set; }
        public string CompileName { get; set; }
        public string TagWord { get; set; }
        public string Keyword { get; set; }
        public string SourceName { get; set; }
        public string SourceAddress { get; set; }
        public string NewsContent { get; set; }
        public Nullable<int> PV { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
        public Nullable<int> SortCode { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<int> EnabledMark { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
    }
}
