//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_material
    {
        public string bm_guid { get; set; }
        public string bm_materialname { get; set; }
        public string bm_materialcode { get; set; }
        public string bm_materialmodel { get; set; }
        public Nullable<double> bm_materialcount { get; set; }
        public string bm_materialunit { get; set; }
        public string bm_materialfac { get; set; }
        public Nullable<System.DateTime> bm_planarrtime { get; set; }
        public string bc_guid_materialtype { get; set; }
        public string bc_guid_materialstatus { get; set; }
        public string bm_extjson { get; set; }
        public Nullable<System.DateTime> bm_updatetime { get; set; }
    }
}
