//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_materialelements
    {
        public string bme_guid { get; set; }
        public string bme_materialid { get; set; }
        public string bme_elementids { get; set; }
        public Nullable<System.DateTime> bme_createtime { get; set; }
        public Nullable<System.DateTime> bme_updatetime { get; set; }
    }
}
