//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_organizeplus
    {
        public string bop_guid { get; set; }
        public string bop_organizeId { get; set; }
        public string bop_modelId { get; set; }
        public string bop_planId { get; set; }
        public string bop_modelphase { get; set; }
    }
}
