//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_schedule
    {
        public string ScheduleId { get; set; }
        public string ScheduleName { get; set; }
        public string ScheduleContent { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string StartTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> Early { get; set; }
        public Nullable<int> IsMailAlert { get; set; }
        public Nullable<int> IsMobileAlert { get; set; }
        public Nullable<int> IsWeChatAlert { get; set; }
        public Nullable<int> ScheduleState { get; set; }
        public Nullable<int> SortCode { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<int> EnabledMark { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
        public string OrganizeId { get; set; }
        public string TaskTypeId { get; set; }
        public int Security { get; set; }
    }
}
