//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_issue_talk
    {
        public string Issue_TalkId { get; set; }
        public string IssueId { get; set; }
        public string UserId { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ContentType { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public string UserOfUnRead { get; set; }
        public string Issue_PTalkId { get; set; }
        public string CommentPatchGUID { get; set; }
    }
}
