//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_orgimg
    {
        public string boi_id { get; set; }
        public string organizeId { get; set; }
        public string boi_smallimgurl { get; set; }
        public string boi_originimg { get; set; }
        public string boi_miniimg { get; set; }
    }
}
