//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_organizeextend
    {
        public string OrganizeExtendId { get; set; }
        public string OrganizeId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public string ThumbnailUrl { get; set; }
        public string BIMComposerID { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<bool> IsPersonal { get; set; }
        public string OwnerUnit { get; set; }
        public string ConstructionUnit { get; set; }
        public string DesignUnit { get; set; }
        public Nullable<System.DateTime> ProjectApprovalDate { get; set; }
    }
}
