//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class bimcomp_category
    {
        public string bcc_guid { get; set; }
        public string bcc_organizeId { get; set; }
        public string bcc_name { get; set; }
        public string bcc_code { get; set; }
        public Nullable<int> bcc_curlevelnumber { get; set; }
        public string bcc_description { get; set; }
        public Nullable<System.DateTime> bcc_updatetime { get; set; }
    }
}
