//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfg_urls
    {
        public string cu_guid { get; set; }
        public string cu_entcode { get; set; }
        public string cu_urltype { get; set; }
        public string cu_url { get; set; }
        public string cu_desc { get; set; }
    }
}
