//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_order
    {
        public string OrderId { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string SellerId { get; set; }
        public string SellerName { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderCode { get; set; }
        public Nullable<decimal> DiscountSum { get; set; }
        public Nullable<decimal> Accounts { get; set; }
        public Nullable<decimal> ReceivedAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<int> PaymentState { get; set; }
        public Nullable<decimal> SaleCost { get; set; }
        public string AbstractInfo { get; set; }
        public string ContractCode { get; set; }
        public string ContractFile { get; set; }
        public Nullable<int> SortCode { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<int> EnabledMark { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
    }
}
