//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_customer
    {
        public string CustomerId { get; set; }
        public string EnCode { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string CustIndustryId { get; set; }
        public string CustTypeId { get; set; }
        public string CustLevelId { get; set; }
        public string CustDegreeId { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string Mobile { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string QQ { get; set; }
        public string Email { get; set; }
        public string Wechat { get; set; }
        public string Hobby { get; set; }
        public string LegalPerson { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanySite { get; set; }
        public string CompanyDesc { get; set; }
        public string TraceUserId { get; set; }
        public string TraceUserName { get; set; }
        public Nullable<System.DateTime> AlertDateTime { get; set; }
        public Nullable<int> AlertState { get; set; }
        public Nullable<int> SortCode { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<int> EnabledMark { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
    }
}
