//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_pdf_cache
    {
        public string Com_pdf_cache_ID { get; set; }
        public string PdfId { get; set; }
        public string CacheId { get; set; }
    }
}
