//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class probimEntities : DbContext
    {
        public probimEntities()
            : base("name=probimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<api_drawposinfo> api_drawposinfo { get; set; }
        public virtual DbSet<api_examineattachment> api_examineattachment { get; set; }
        public virtual DbSet<api_examinedata> api_examinedata { get; set; }
        public virtual DbSet<api_examinedataextend> api_examinedataextend { get; set; }
        public virtual DbSet<api_examinedatatype> api_examinedatatype { get; set; }
        public virtual DbSet<api2_invite> api2_invite { get; set; }
        public virtual DbSet<api2_recycles> api2_recycles { get; set; }
        public virtual DbSet<api2_session> api2_session { get; set; }
        public virtual DbSet<api2_suscribe> api2_suscribe { get; set; }
        public virtual DbSet<api2_validcode> api2_validcode { get; set; }
        public virtual DbSet<auth_rolephase> auth_rolephase { get; set; }
        public virtual DbSet<base_area> base_area { get; set; }
        public virtual DbSet<base_authorize> base_authorize { get; set; }
        public virtual DbSet<base_authorizedata> base_authorizedata { get; set; }
        public virtual DbSet<base_category> base_category { get; set; }
        public virtual DbSet<base_coderule> base_coderule { get; set; }
        public virtual DbSet<base_coderuleseed> base_coderuleseed { get; set; }
        public virtual DbSet<base_companydata> base_companydata { get; set; }
        public virtual DbSet<base_databasebackup> base_databasebackup { get; set; }
        public virtual DbSet<base_databaselink> base_databaselink { get; set; }
        public virtual DbSet<base_dataitem> base_dataitem { get; set; }
        public virtual DbSet<base_dataitemdetail> base_dataitemdetail { get; set; }
        public virtual DbSet<base_department> base_department { get; set; }
        public virtual DbSet<base_file> base_file { get; set; }
        public virtual DbSet<base_filefolder> base_filefolder { get; set; }
        public virtual DbSet<base_fileinfo> base_fileinfo { get; set; }
        public virtual DbSet<base_fileinfo_version> base_fileinfo_version { get; set; }
        public virtual DbSet<base_filterip> base_filterip { get; set; }
        public virtual DbSet<base_filtertime> base_filtertime { get; set; }
        public virtual DbSet<base_issue> base_issue { get; set; }
        public virtual DbSet<base_issue_talk> base_issue_talk { get; set; }
        public virtual DbSet<base_issue_user> base_issue_user { get; set; }
        public virtual DbSet<base_issuenewrelation> base_issuenewrelation { get; set; }
        public virtual DbSet<base_log> base_log { get; set; }
        public virtual DbSet<base_logext> base_logext { get; set; }
        public virtual DbSet<base_material> base_material { get; set; }
        public virtual DbSet<base_materialelements> base_materialelements { get; set; }
        public virtual DbSet<base_materialrecord> base_materialrecord { get; set; }
        public virtual DbSet<base_messagequeue> base_messagequeue { get; set; }
        public virtual DbSet<base_module> base_module { get; set; }
        public virtual DbSet<base_modulebutton> base_modulebutton { get; set; }
        public virtual DbSet<base_modulecolumn> base_modulecolumn { get; set; }
        public virtual DbSet<base_moduleform> base_moduleform { get; set; }
        public virtual DbSet<base_moduleforminstance> base_moduleforminstance { get; set; }
        public virtual DbSet<base_newlog> base_newlog { get; set; }
        public virtual DbSet<base_news> base_news { get; set; }
        public virtual DbSet<base_organize> base_organize { get; set; }
        public virtual DbSet<base_organizedetail> base_organizedetail { get; set; }
        public virtual DbSet<base_organizeextend> base_organizeextend { get; set; }
        public virtual DbSet<base_organizegis> base_organizegis { get; set; }
        public virtual DbSet<base_organizeplus> base_organizeplus { get; set; }
        public virtual DbSet<base_orgimg> base_orgimg { get; set; }
        public virtual DbSet<base_projectnews> base_projectnews { get; set; }
        public virtual DbSet<base_projectscore> base_projectscore { get; set; }
        public virtual DbSet<base_projecttemplate> base_projecttemplate { get; set; }
        public virtual DbSet<base_publicextend> base_publicextend { get; set; }
        public virtual DbSet<base_relation> base_relation { get; set; }
        public virtual DbSet<base_role> base_role { get; set; }
        public virtual DbSet<base_schedule> base_schedule { get; set; }
        public virtual DbSet<base_schedule_attachment> base_schedule_attachment { get; set; }
        public virtual DbSet<base_schedule_participant> base_schedule_participant { get; set; }
        public virtual DbSet<base_specialpw> base_specialpw { get; set; }
        public virtual DbSet<base_template_folder> base_template_folder { get; set; }
        public virtual DbSet<base_user> base_user { get; set; }
        public virtual DbSet<base_userext> base_userext { get; set; }
        public virtual DbSet<base_userrelation> base_userrelation { get; set; }
        public virtual DbSet<base_usertag> base_usertag { get; set; }
        public virtual DbSet<bimcomp_attach> bimcomp_attach { get; set; }
        public virtual DbSet<bimcomp_category> bimcomp_category { get; set; }
        public virtual DbSet<bimcomp_family> bimcomp_family { get; set; }
        public virtual DbSet<bimcomp_faprop> bimcomp_faprop { get; set; }
        public virtual DbSet<bimcomp_fapropcategory> bimcomp_fapropcategory { get; set; }
        public virtual DbSet<bimcomp_file> bimcomp_file { get; set; }
        public virtual DbSet<bimcomp_relmodel> bimcomp_relmodel { get; set; }
        public virtual DbSet<bimcomp_reltag> bimcomp_reltag { get; set; }
        public virtual DbSet<bimcomp_tag> bimcomp_tag { get; set; }
        public virtual DbSet<cfg_urls> cfg_urls { get; set; }
        public virtual DbSet<client_cashbalance> client_cashbalance { get; set; }
        public virtual DbSet<client_chance> client_chance { get; set; }
        public virtual DbSet<client_customer> client_customer { get; set; }
        public virtual DbSet<client_customercontact> client_customercontact { get; set; }
        public virtual DbSet<client_expenses> client_expenses { get; set; }
        public virtual DbSet<client_invoice> client_invoice { get; set; }
        public virtual DbSet<client_order> client_order { get; set; }
        public virtual DbSet<client_orderentry> client_orderentry { get; set; }
        public virtual DbSet<client_receivable> client_receivable { get; set; }
        public virtual DbSet<client_trailrecord> client_trailrecord { get; set; }
        public virtual DbSet<com_pdf_cache> com_pdf_cache { get; set; }
        public virtual DbSet<email_addressee> email_addressee { get; set; }
        public virtual DbSet<email_category> email_category { get; set; }
        public virtual DbSet<email_content> email_content { get; set; }
        public virtual DbSet<errno> errno { get; set; }
        public virtual DbSet<exam_category> exam_category { get; set; }
        public virtual DbSet<im_content> im_content { get; set; }
        public virtual DbSet<im_group> im_group { get; set; }
        public virtual DbSet<im_read> im_read { get; set; }
        public virtual DbSet<im_usergroup> im_usergroup { get; set; }
        public virtual DbSet<issue_status> issue_status { get; set; }
        public virtual DbSet<issue_tag> issue_tag { get; set; }
        public virtual DbSet<issue_type> issue_type { get; set; }
        public virtual DbSet<msg_msg> msg_msg { get; set; }
        public virtual DbSet<msg_msgext> msg_msgext { get; set; }
        public virtual DbSet<msg_user> msg_user { get; set; }
        public virtual DbSet<mtr_outerpage> mtr_outerpage { get; set; }
        public virtual DbSet<oper_log> oper_log { get; set; }
        public virtual DbSet<org_userorganize> org_userorganize { get; set; }
        public virtual DbSet<panorama_base> panorama_base { get; set; }
        public virtual DbSet<panorama_pointinfo> panorama_pointinfo { get; set; }
        public virtual DbSet<plus_project> plus_project { get; set; }
        public virtual DbSet<plus_resource> plus_resource { get; set; }
        public virtual DbSet<plus_task3> plus_task3 { get; set; }
        public virtual DbSet<plusrel_taskelements> plusrel_taskelements { get; set; }
        public virtual DbSet<rel_issue_issueuser> rel_issue_issueuser { get; set; }
        public virtual DbSet<rel_issue_tag> rel_issue_tag { get; set; }
        public virtual DbSet<rpt_temp> rpt_temp { get; set; }
        public virtual DbSet<shared_model> shared_model { get; set; }
        public virtual DbSet<sync_materialarrange> sync_materialarrange { get; set; }
        public virtual DbSet<wechat_app> wechat_app { get; set; }
        public virtual DbSet<wechat_deptrelation> wechat_deptrelation { get; set; }
        public virtual DbSet<wechat_userrelation> wechat_userrelation { get; set; }
        public virtual DbSet<wf_delegaterecord> wf_delegaterecord { get; set; }
        public virtual DbSet<wf_delegaterule> wf_delegaterule { get; set; }
        public virtual DbSet<wf_delegateruleschemeinfo> wf_delegateruleschemeinfo { get; set; }
        public virtual DbSet<wf_fieldcfg> wf_fieldcfg { get; set; }
        public virtual DbSet<wf_flowinstance> wf_flowinstance { get; set; }
        public virtual DbSet<wf_flowinstanceactive> wf_flowinstanceactive { get; set; }
        public virtual DbSet<wf_flowrecord> wf_flowrecord { get; set; }
        public virtual DbSet<wf_frmmain> wf_frmmain { get; set; }
        public virtual DbSet<wf_linebtns> wf_linebtns { get; set; }
        public virtual DbSet<wf_nodedatas> wf_nodedatas { get; set; }
        public virtual DbSet<wf_processinstance> wf_processinstance { get; set; }
        public virtual DbSet<wf_processoperationhistory> wf_processoperationhistory { get; set; }
        public virtual DbSet<wf_processscheme> wf_processscheme { get; set; }
        public virtual DbSet<wf_processtransitionhistory> wf_processtransitionhistory { get; set; }
        public virtual DbSet<wf_projectschemerelation> wf_projectschemerelation { get; set; }
        public virtual DbSet<wf_schemecontent> wf_schemecontent { get; set; }
        public virtual DbSet<wf_schemeinfo> wf_schemeinfo { get; set; }
        public virtual DbSet<wf_schemeinfoauthorize> wf_schemeinfoauthorize { get; set; }
        public virtual DbSet<api_examinerectification> api_examinerectification { get; set; }
        public virtual DbSet<base_module_bak> base_module_bak { get; set; }
        public virtual DbSet<base_organizeextendbak> base_organizeextendbak { get; set; }
        public virtual DbSet<base_projectnews_copy> base_projectnews_copy { get; set; }
        public virtual DbSet<base_user_bak> base_user_bak { get; set; }
        public virtual DbSet<del_plustask1> del_plustask1 { get; set; }
        public virtual DbSet<del_plustask2> del_plustask2 { get; set; }
        public virtual DbSet<ipwhite> ipwhite { get; set; }
        public virtual DbSet<plus_task> plus_task { get; set; }
        public virtual DbSet<plus_task_originbak> plus_task_originbak { get; set; }
        public virtual DbSet<share_doc> share_doc { get; set; }
        public virtual DbSet<sysloginlog> sysloginlog { get; set; }
    }
}
