//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_addressee
    {
        public string AddresseeId { get; set; }
        public string ContentId { get; set; }
        public string CategoryId { get; set; }
        public string RecipientId { get; set; }
        public string RecipientName { get; set; }
        public Nullable<int> RecipientState { get; set; }
        public Nullable<int> IsRead { get; set; }
        public Nullable<int> ReadCount { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<int> IsHighlight { get; set; }
        public Nullable<int> Backlog { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
    }
}
