//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_content
    {
        public string ContentId { get; set; }
        public string CategoryId { get; set; }
        public string ParentId { get; set; }
        public string Theme { get; set; }
        public string ThemeColor { get; set; }
        public string EmailContent { get; set; }
        public Nullable<int> EmailType { get; set; }
        public string SenderId { get; set; }
        public string SenderName { get; set; }
        public Nullable<System.DateTime> SenderTime { get; set; }
        public Nullable<int> IsHighlight { get; set; }
        public string SendPriority { get; set; }
        public Nullable<int> IsSmsReminder { get; set; }
        public Nullable<int> IsReceipt { get; set; }
        public string AddresssHtml { get; set; }
        public string CopysendHtml { get; set; }
        public string BccsendHtml { get; set; }
        public Nullable<int> SendState { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<int> EnabledMark { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
    }
}
