//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam_category
    {
        public string ec_guid { get; set; }
        public string ec_organizeId { get; set; }
        public string ec_type { get; set; }
        public string ec_name { get; set; }
        public string ec_code { get; set; }
        public int ec_curlevelnumber { get; set; }
        public string ec_elementids { get; set; }
    }
}
