//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class msg_user
    {
        public string mu_guid { get; set; }
        public string mm_guid { get; set; }
        public string userId { get; set; }
        public string mu_hasread { get; set; }
        public string mu_hasalert { get; set; }
    }
}
