//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class msg_msg
    {
        public string mm_guid { get; set; }
        public string mm_tritype { get; set; }
        public string mm_triobjtype { get; set; }
        public string mm_objid { get; set; }
        public string mm_objname { get; set; }
        public string mm_author { get; set; }
        public string mm_type { get; set; }
        public string mm_authorrealname { get; set; }
        public string mm_triobjobjtype { get; set; }
        public string mm_createdatetime { get; set; }
        public string mm_organizeid { get; set; }
    }
}
