//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class panorama_pointinfo
    {
        public string pp_guid { get; set; }
        public string pbguid { get; set; }
        public string pp_scene { get; set; }
        public string pp_posv2 { get; set; }
        public string pp_name { get; set; }
        public string pp_pos { get; set; }
        public string pp_hotspot { get; set; }
    }
}
