//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class plus_task_originbak
    {
        public string UID_ { get; set; }
        public Nullable<int> ID_ { get; set; }
        public string NAME_ { get; set; }
        public Nullable<System.DateTime> START_ { get; set; }
        public Nullable<System.DateTime> FINISH_ { get; set; }
        public Nullable<int> DURATION_ { get; set; }
        public Nullable<int> WORK_ { get; set; }
        public Nullable<int> PERCENTCOMPLETE_ { get; set; }
        public Nullable<int> MANUAL_ { get; set; }
        public Nullable<int> WEIGHT_ { get; set; }
        public Nullable<int> CONSTRAINTTYPE_ { get; set; }
        public Nullable<System.DateTime> CONSTRAINTDATE_ { get; set; }
        public Nullable<int> MILESTONE_ { get; set; }
        public Nullable<int> SUMMARY_ { get; set; }
        public Nullable<int> CRITICAL_ { get; set; }
        public Nullable<int> PRIORITY_ { get; set; }
        public string NOTES_ { get; set; }
        public string DEPARTMENT_ { get; set; }
        public string PRINCIPAL_ { get; set; }
        public string PREDECESSORLINK_ { get; set; }
        public Nullable<int> FIXEDDATE_ { get; set; }
        public string PARENTTASKUID_ { get; set; }
        public string PROJECTUID_ { get; set; }
        public Nullable<System.DateTime> ACTUALSTART_ { get; set; }
        public Nullable<System.DateTime> ACTUALFINISH_ { get; set; }
        public Nullable<int> ACTUALDURATION_ { get; set; }
        public string ASSIGNMENTS_ { get; set; }
        public string WBS_ { get; set; }
        public Nullable<int> CRITICAL2_ { get; set; }
    }
}
