//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class plus_resource
    {
        public string UID_ { get; set; }
        public string NAME_ { get; set; }
        public Nullable<int> TYPE_ { get; set; }
        public Nullable<int> MAXUNITS_ { get; set; }
        public Nullable<int> WORK_ { get; set; }
        public string PROJECTUID_ { get; set; }
        public Nullable<double> COST_ { get; set; }
    }
}
