//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class plusrel_taskelements
    {
        public string pte_guid { get; set; }
        public string pte_planid { get; set; }
        public string pte_taskid { get; set; }
        public string pte_elementids { get; set; }
        public Nullable<System.DateTime> pte_createtime { get; set; }
        public Nullable<System.DateTime> pte_updatetime { get; set; }
    }
}
