//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class rel_issue_issueuser
    {
        public System.Guid riiu_guid { get; set; }
        public System.Guid riiu_issueid { get; set; }
        public System.Guid riiu_userid { get; set; }
        public string riiu_reltype { get; set; }
    }
}
