//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class share_doc
    {
        public string shd_Guid { get; set; }
        public string shd_SessionId { get; set; }
        public string shd_BIMComposerId { get; set; }
        public string shd_DocIds { get; set; }
        public string shd_Privilege { get; set; }
        public Nullable<System.DateTime> shd_CreateDate { get; set; }
        public Nullable<int> shd_EndTime { get; set; }
        public Nullable<int> shd_HasPwd { get; set; }
        public string shd_Pwd { get; set; }
        public string CreateUserId { get; set; }
    }
}
