//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class shared_model
    {
        public System.Guid shm_guid { get; set; }
        public Nullable<System.Guid> shm_sessionId { get; set; }
        public Nullable<System.Guid> shm_projectid { get; set; }
        public Nullable<System.Guid> shm_modelid { get; set; }
        public string shm_json { get; set; }
        public Nullable<System.DateTime> shm_createdate { get; set; }
        public string shm_pwd { get; set; }
        public Nullable<bool> shm_haspwd { get; set; }
        public string shm_modelversion { get; set; }
        public string shm_createUserId { get; set; }
        public string shm_originpwd { get; set; }
    }
}
