//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class wf_flowinstance
    {
        public string WFI_Id { get; set; }
        public string SC_Id { get; set; }
        public string WFI_Title { get; set; }
        public string WFI_CreateUser { get; set; }
        public Nullable<System.DateTime> WFI_CreateTime { get; set; }
        public string WFI_ActiveNodeIds { get; set; }
        public Nullable<int> WFI_Status { get; set; }
        public Nullable<System.DateTime> WFI_UpdateTime { get; set; }
        public string WFI_NextOperators { get; set; }
        public string WFI_AllOperators { get; set; }
        public string WFI_UniqueId { get; set; }
        public string WFI_Nexts { get; set; }
        public string WFI_FormData { get; set; }
    }
}
