//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class wf_flowrecord
    {
        public string WFR_ID { get; set; }
        public string WFI_Id { get; set; }
        public string WFR_PNodeId { get; set; }
        public string WFR_CNodeId { get; set; }
        public Nullable<System.DateTime> WFR_Createtime { get; set; }
        public string WFR_Operator { get; set; }
        public string WFR_OperateResult { get; set; }
        public string WFR_Comments { get; set; }
        public string WFR_FormData { get; set; }
    }
}
