//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelNet45
{
    using System;
    using System.Collections.Generic;
    
    public partial class wf_processscheme
    {
        public string Id { get; set; }
        public string SchemeContent { get; set; }
        public string WFSchemeInfoId { get; set; }
        public string SchemeVersion { get; set; }
        public int ProcessType { get; set; }
        public string ModelID { get; set; }
        public string ViewpointID { get; set; }
        public string ElementID { get; set; }
        public string SpaceID { get; set; }
    }
}
